parameters:
    superrb_google_recaptcha.site_key: '%env(SUPERRB_GOOGLE_RECAPTCHA_SITE_KEY)%'
    superrb_google_recaptcha.secret_key: '%env(SUPERRB_GOOGLE_RECAPTCHA_SECRET_KEY)%'
    superrb_google_recaptcha.api_url: https://www.google.com/recaptcha/api/siteverify
    superrb_google_recaptcha.src_url: "https://www.google.com/recaptcha/api.js?render=%superrb_google_recaptcha.site_key%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Superrb\GoogleRecaptchaBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Superrb\GoogleRecaptchaBundle\Service\GoogleRecaptchaService:
        arguments:
            - "@logger"
            - "%superrb_google_recaptcha.secret_key%"
            - "%superrb_google_recaptcha.api_url%"

    Superrb\GoogleRecaptchaBundle\Twig\AppExtension:
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@twig"
            - "%superrb_google_recaptcha.site_key%"
            - "%superrb_google_recaptcha.src_url%"
